repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=no]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: forbid-submodules
  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.31.7
    hooks:
      - id: basedpyright
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "0.9.2"
    hooks:
      - id: pyproject-fmt
